src/duplitree/config/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include('tree.urls')),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls() + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/duplitree/tree/urls.py
from django.urls import path

from .views import TreeDetailView, TreeListView, TreePathView, FileDeleteView, FileDetailView

app_name = 'tree'


urlpatterns = [
    path('tree/', TreeListView.as_view(), name='list'),
    path('tree/<int:pk>/', TreeDetailView.as_view(), name='detail'),
    path('tree/<int:pk>/<path:path>/', TreePathView.as_view(), name='directory'),
    path('file/<int:pk>/', FileDetailView.as_view(), name='file'),
    path('file/<int:pk>/delete/', FileDeleteView.as_view(), name='file-delete'),
]

src/duplitree/tree/models.py
import hashlib
import os
from datetime import datetime
from pathlib import Path

from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.utils.timezone import make_aware, get_default_timezone
from .managers import FileManager, DirectoryManager


FA_ICON_MAPPING = {
    'pdf': 'fa-file-pdf',
    'doc': 'fa-file-word',
    'docx': 'fa-file-word',
    'xls': 'fa-file-excel',
    'xlsx': 'fa-file-excel',
    'ppt': 'fa-file-powerpoint',
    'pptx': 'fa-file-powerpoint',
    'jpg': 'fa-file-image',
    'jpeg': 'fa-file-image',
    'png': 'fa-file-image',
    'gif': 'fa-file-image',
    'txt': 'fa-file-lines',
    'zip': 'fa-file-archive',
    'rar': 'fa-file-archive',
    'mp3': 'fa-file-audio',
    'wav': 'fa-file-audio',
    'mp4': 'fa-file-video',
    'mov': 'fa-file-video',
    'avi': 'fa-file-video',
}


class HashAlgorithm(models.TextChoices):
    MD5 = 'md5', 'MD5'
    SHA1 = 'sha1', 'SHA-1'
    SHA224 = 'sha224', 'SHA-224'
    SHA256 = 'sha256', 'SHA-256'
    SHA384 = 'sha384', 'SHA-384'
    SHA512 = 'sha512', 'SHA-512'
    BLAKE2B = 'blake2b', 'BLAKE2b'
    BLAKE2S = 'blake2s', 'BLAKE2s'


class Tree(models.Model):
    algorithm = models.CharField(
        _("Algorithmus"),
        max_length=10,
        choices=HashAlgorithm.choices,
        default=HashAlgorithm.MD5,
        help_text="Wählen Sie den zugrunde liegenden Hash-Algorithmus."
    )
    base_path = models.CharField(
        max_length=1024,  # Maximal 1024 Zeichen, ausreichend für die meisten Dateisysteme
        help_text="Pfad zum Verzeichnis oder zur Datei.",
    )

    def get_hash_function(self):
        return hashlib.new(self.algorithm)

    def scan(self):
        base_path = str(self.base_path)
        for root, dirs, files in os.walk(base_path):
            rel_path = root.lstrip(base_path)
            directory = Directory.objects.get_or_create(
                tree=self,
                path=rel_path,
                name=os.path.basename(rel_path),
            )[0]
            for name in dirs:
                Directory.objects.get_or_create(
                    tree=self,
                    parent=directory,
                    path=os.path.join(rel_path, name),
                    name=name,
                )
            for name in files:
                File.objects.get_or_create(
                    directory=directory,
                    name=name,
                )

    class Meta:
        verbose_name = _("Dateibaum")
        verbose_name_plural = _("Dateibäume")


class FilesystemEntity(models.Model):
    name = models.CharField(
        _("Name"),
        max_length=50,
    )
    size = models.BigIntegerField(
        _("Größe"),
        blank=True, null=True,
    )
    hash = models.CharField(
        _("Hash"),
        max_length=32,
        blank=True, null=True,
    )
    created = models.DateTimeField(
        _("Erstellt"),
        blank=True, null=True,
    )
    updated = models.DateTimeField(
        _("Geändert"),
        blank=True, null=True
    )

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Directory(FilesystemEntity):
    type = 'directory'
    tree = models.ForeignKey(
        Tree,
        related_name="directories",
        on_delete=models.CASCADE,
    )
    parent = models.ForeignKey(
        "self",
        related_name="subdirectories",
        on_delete=models.CASCADE,
        blank=True, null=True,
    )
    name = models.CharField(
        _("Name"),
        max_length=50,
        blank=True,
    )
    path = models.CharField(
        _("Relativer Pfad"),
        max_length=1024,
    )
    objects = DirectoryManager()

    @property
    def absolute_path(self):
        return Path(self.tree.base_path) / self.path.lstrip('/')

    def get_absolute_url(self):
        if self.path == '':
            return reverse('tree:detail', kwargs={'pk': self.tree.pk})
        return reverse('tree:directory', kwargs={'pk':self.tree.pk, 'path': self.path.lstrip('/')})

    class Meta:
        verbose_name = _("Verzeichnis")
        verbose_name_plural = _("Verzeichnisse")
        ordering = ['path']
        unique_together = ['tree', 'path']


class File(FilesystemEntity):
    type = 'file'
    directory = models.ForeignKey(
        Directory,
        related_name="files",
        on_delete=models.CASCADE,
    )
    objects = FileManager()

    @property
    def absolute_path(self):
        return self.directory.absolute_path / self.name

    @property
    def fa_icon(self):
        extension = self.name.split('.')[-1].lower()
        return FA_ICON_MAPPING.get(extension, "fa-file")

    def read_metadata(self, save=True):
        """
        Liest die Metadaten der Datei aus und aktualisiert die entsprechenden Felder.
        """
        file_path = self.absolute_path
        file_stat = os.stat(file_path)

        self.size = file_stat.st_size
        self.created = make_aware(datetime.fromtimestamp(file_stat.st_ctime), timezone=get_default_timezone())
        self.updated = make_aware(datetime.fromtimestamp(file_stat.st_mtime), timezone=get_default_timezone())
        if save:
            self.save()

    def hash_file(self, save=True):
        """
        Berechnet den Hash-Wert der Datei und speichert ihn im Feld `hash`.
        """
        hash_function = self.directory.tree.get_hash_function()
        with open(self.absolute_path, 'rb') as f:
            for chunk in iter(lambda: f.read(4096), b''):
                hash_function.update(chunk)
        self.hash = hash_function.hexdigest()
        if save:
            self.save()

        class Meta:
            verbose_name = _("Datei")
            verbose_name_plural = _("Dateien")
            unique_together = ['directory', 'name']

'''
def bulk_save(files):
    """
    Speichert eine Liste von File-Instanzen in einer Bulk-Aktion.
    """
    File.objects.bulk_update(files, ['size', 'created', 'updated'])
'''

src/duplitree/tree/views.py
from django.db.models.functions import Replace, Length
from django.views.generic import DetailView, ListView, DeleteView
from django.db.models import OuterRef, Subquery, Count, Q, Value
from .models import Tree, File
from django.db import models


class TreeListView(ListView):
    model = Tree


class TreeDetailView(DetailView):
    model = Tree

    def get_context_data(self, **kwargs):
        selected_path = self.kwargs.get('path', "")
        depth = selected_path.count('/')
        if selected_path:
            depth += 1
        return {
            **super().get_context_data(**kwargs),
            "directories": self.get_directory_queryset(selected_path),
            "files": self.get_file_queryset(selected_path),
            "selected_path": selected_path,
            "depth": depth,
            "show_depth": depth + 1,
        }

    def get_directory_queryset(self, selected_path):
        qs = self.object.directories.all()
        qs = qs.annotate_is_open(selected_path)
        qs = qs.annotate_depth()
        #qs = qs.annotate_size()
        return qs

    def get_file_queryset(self, selected_path):
        qs = File.objects.filter(
            directory__tree=self.object,
            directory__path=selected_path,
        )
        qs = qs.annotate_depth()
        qs = qs.annotate_same_hash_count()
        return qs

class TreePathView(TreeDetailView):
    pass


class FileDetailView(DetailView):
    model = File
    template_name = "tree/file_modal.html"

class FileDeleteView(DeleteView):
    model = File

src/duplitree/htmx/templates/htmx/base.html
{% extends 'base.html' %}

{% comment %}
This is the base template for all htmx templates. It extends the base.html template
{% endcomment %}

src/duplitree/htmx/templates/htmx/content.html
{% extends request.htmx|yesno:"htmx/standalone.html,htmx/base.html" %}

{% block content %}
  {% if request.htmx %}
    <h1 id="modal-title" class="modal-title" hx-swap-oob="true">
      {% block "page_title" %}{% endblock %}
    </h1>
    {% block "header" %}{% endblock %}
  {% endif %}
  {% block "content" %}{% endblock %}
{% endblock %}

src/duplitree/htmx/templates/htmx/modal/button.html
{# Loads Content into the main modal #}
<button
        type="button"
        class="btn btn-{% if type %}{{ type }}{% else %}link{% endif %} {{ classes }}"
        hx-get="{{ url }}"
        hx-swap="none"
        hx-indicator="#modal-spinner"
        hx-push-url="{% if push_url %}{{ push_url }}{% else %}false{% endif %}"
        onclick="showModal();">
    {{ text }}
</button>

src/duplitree/htmx/templates/htmx/modal/link.html
{% comment %}
This creates a link using hx-boost.
Use this if you want to create a hybride View that is usable as modal or standalone.
{% endcomment %}
<a
        class="btn btn-{% if type %}{{ type }}{% else %}link{% endif %} {{ classes }}"
        href="{{ url }}"
        role="button"
        hx-boost="true"
        hx-swap="none"
        hx-indicator="#modal-spinner"
        hx-push-url="{% if push_url %}{{ push_url }}{% else %}false{% endif %}"
        onclick="showModal();">
    {{ text }}
</a>

src/duplitree/htmx/templates/htmx/modal/modal.html
{% load i18n %}

<div id="modal" class="modal fade" tabindex="-1" hx-swap-oob="innerHTML">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl modal-fullscreen-lg-down">
    {% block modal-content %}
      <div id="modal-content" class="modal-content">
        <div id="modal-spinner" class="htmx-indicator d-flex justify-content-center position-absolute w-100 h-100 bg-white" style="z-index:100;">
          <div class="spinner-border m-auto" role="status">
            <span class="visually-hidden">{% trans 'Lade' %}...</span>
          </div>
        </div>
        <div id="modal-header" class="modal-header">
          {% block modal-header %}
            {% block modal-title %}
              <h5 id="modal-title" class="modal-title"></h5>
            {% endblock modal-title %}
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          {% endblock modal-header %}
        </div>
        <div id="modal-body" class="modal-body">
          {% block modal-body %}
            {% block content %}
            {% endblock content %}
          {% endblock modal-body %}
        </div>
        <div id="modal-footer" class="modal-footer">
          {% block modal-footer %}
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'Schließen' %}</button>
          {% endblock modal-footer %}
        </div>
      </div>
    {% endblock modal-content %}
  </div>
</div>

src/duplitree/htmx/templates/htmx/modal/wrapper.html
{% extends request.htmx|yesno:"htmx/modal/modal.html,htmx/base.html" %}

src/duplitree/htmx/templates/htmx/standalone.html
{% block content %}{% endblock %}

src/duplitree/tree/templates/base.html
{% load static django_htmx htmx %}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Duplitree{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'fontawesome/6.7.2/css/all.min.css' %}" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="{% static 'fontawesome/6.7.2/js/all.min.js' %}" integrity="sha512-b+nQTCdtTBIRIbraqNEwsjB6UvL3UEMkXnhzd8awtCYh0Kcsjl9uEgwVFVbhoj3uu1DO1ZMacNvLoyJJiNfcvg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% htmx_head %}
</head>
<body>
    <header>
    </header>
    <main>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h2>{% block page_title %}Duplitree{% endblock %}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </main>
    <footer>
    </footer>
    {% include 'htmx/modal/modal.html' %}
    {% django_htmx_script %}
</body>
</html>

src/duplitree/tree/templates/tree/directory.html
<div class="row">
    <div class="col-auto" style="margin-left: {% widthratio directory.depth 1 20 %}px;">
        <a href="{{ directory.get_absolute_url }}" class="btn btn-link text-dark text-decoration-none p-0">
            <i class="fa-regular fa-folder{% if directory.is_open %}-open{% endif %}"></i>
             {{ directory }} depth:{{ directory.depth }}
        </a>
    </div>
    <div class="col">
        Size: {{ directory.size }}
    </div>
</div>

src/duplitree/tree/templates/tree/entity.html
{% load filesize %}
<div class="row">
    <div class="col-auto" style="margin-left: {% widthratio entity.depth 1 20 %}px;">
        <i class="fa-regular {{ entity.fa_icon }}"></i> {{ entity.name }}
    </div>
    <div class="col d-flex justify-content-end">
        same_hash_count: {{ entity.same_hash_count }}
        <i class="fa-solid fa-layer-group"></i> {{ entity.depth }}
        <i class="fa-solid fa-hashtag"></i> {{ entity.hash }}
        <i class="fa-solid fa-compact-disc"></i> {{ entity.size | human_readable_size }}
    </div>
    <div class="col">
        {% url 'tree:file' pk=file.pk as url %}
        {% include 'htmx/modal/link.html' with text='<i class="fa-solid fa-bars"></i>' url=url classes='p-0' %}
    </div>
</div>

src/duplitree/tree/templates/tree/file.html
{% include './entity.html' with entity=file %}

src/duplitree/tree/templates/tree/file_modal.html
{% extends 'htmx/modal/wrapper.html' %}

{% block content %}
fdsaf
{% endblock%}

src/duplitree/tree/templates/tree/tree_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Tree List {{ object }}</h1>
    {{ object.root }}
depth:{{depth}}

    <div class="container">
        <div class="row">
            <div class="col-12">
                {% for directory in directories %}
                    {% if directory.depth <= show_depth %}
                        {% include "./directory.html" %}
                    {% endif %}
                    {% if directory.is_open and directory.path == selected_path %}
                        {% for file in files %}
                            {% include "./file.html" %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

src/duplitree/tree/templates/tree/tree_list.html
{% extends "./base.html" %}

{% block content %}
    <h1>Tree List</h1>
    <ul>
        {% for tree in object_list %}
            <li><a href="{% url 'tree:detail' pk=tree.pk %}">{{ tree.id }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}